sudo: required
dist: trusty
addons:
  artifacts:
    paths:
      - results
  apt:
    sources:
      - google-chrome
    packages:
      - google-chrome-stable
language: node_js
node_js:
  - '7'
cache:
  directories:
    - node_modules
    - bower_components
    - $HOME/.npm
    - $HOME/.cache
before_script:
  - npm install
before_deploy:
  - npm run build
env:
  global:
    - NODE_ENV=testing
    - ARTIFACTS_BUCKET=js-tasks-ru
    - secure: >-
        PO/kflMTwgC76LljdhjxPOTiF0QuQESiseZZy3z8f7Bn7Kt06cOWaRZ8yBm/pcbZIOmD3cePt3iJgGbZbHfYyC6zgOyi2aLrctgZyLDetaC+38YCKKX5sA0D/t0RtSg+Mq+NEvdw/sBydQkOS3S3hK0Yw5iIupErVVUY+lLMXWFy9s7b80aXUfK2yukcapGCtZjeIjHy7DIrZUf6E0g+wyiaee1AA/vloM8YlEf/V9zyuKEjkHSry8rmdfWll8TMkcTeyw6pa6d7YVDwLwYZDy4o8EOvkGF6Nr5L8CAyFHxhuJlQ0kK+NgXn8ggG+yCB7U7xsVNbar1ffEKa1dP+lVhmw/cT6enE1eJ0PNFPuRkudCp52cutzWnYKvZqd9Ei2jb/4RA4rGbsonap1rjZNANWoZe2P8n+ytxdtP6gku5ZtAqVnx/1KB3nWrkxPTazaQ4LD7/ZQDBvrZ1V1ITuhgP/87dQjrH1ETGvJQjbFlFmAEwVdcyAaDJ598emHUdIrV3gnR4gFaGjzx65w2CdQlXB5TeqxxvkxVjoTXrUUvmxRHmNWAOGMREnUGDUdzHpYDs+WM1AglRq7iZD1YAKCmIqzNopvUvawmI9wDc/nRO7IvW6RtRMTqY+Ac0doAKw14Dqm94uU98xfGEGTyT1qFS/w4HdGn6d1TSdtvf81RI=
    - secure: >-
        DM7WVXNTl1cjHTXumXIPfKwcB02O/L0ql31tPoU8vtaJinyI1HeHpYqHJlDa4EAl4AyTJnVk1nsSlRZZLNUhwBcRoue0+vJNg0LeujV5c6j3YmR0Rs/WjarlNTpP+oqfKCLZDxiOQxlUGVlsQ70ttHkoQbPNBKRhh1+NihCcBXeUu56bjJsaM7BRlkFcnjRPjQ/9p+r1Pxyu7u75XfRso8iWqA3kzToE2eavgNLtF32FtRMQeDgA8DSoyNVT/nBqXJPK1eigzfpYcTQf2nXEi1g7PpJo8RQtkmOO/3R/8SjGph59RH+RJ54Gbf+3FdQCc7441UcuuhiCGcQ6f68Dctm3ZOjwA/mlBxshP53ym8kCRyU9meGO4w41t/94bdLuNg6Zztwy0GGqkQJ31yQy8SRDDfZqkRgM9pyIAD601LwEjBOod2mbZKG14gUze8C/vFGKfbLwCAerTeNsMB9/4+TuGe/oQ1PHoA6f/LiM3RA47JBFjHGa6fbT+ymkahAaw0Vg4ljMj3iUz6vxzgfSp4iGlQ5qQb/CoPr2MlKCIfeYAYH6RFznZJ/BhFS6nau4CUnD4yFxYX0I3b/0WZ6F40v5OPYadRW0bR3oLPxOUr/l2izRLqRt9rQTYNFW34cAL4f14z2GhjjvNMvtD/kLJZQXgumpP9WiXnL0ccbXKXA=
script:
  - npm run test
notifications:
  webhooks: 'http://learn.javascript.ru/automation/ci/build'
